### ISSUE TITLE
Also work without a system tray

### ISSUE THREAD

**Issue by probonopd** [ballessay/snomcontrol#1]
Is it possible to use this application without a system tray?

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/82debf481044bcc3e8dc6c7e05da29b80a0c4b02/database/snomcontrol/screenshot.png)

**Comment by ballessay** [comment]
Nice catch. I haven't considered that. Guess I'll need to remove/disable some menu entries to hide the application than.

Thanks for linuxdeployqt an opening an issue.

**Comment by ballessay** [comment]
Can you give the latest AppImage a try?

**Comment by probonopd** [comment]
Thank you. Looking good :+1:
